### ISSUE TITLE
Feature request: Docker containerised version

### ISSUE THREAD

**Issue by maggie0002** [Razikus/open-balena-dashboard#1]
Fantastic project, a great help. 

I'm going to run this locally and sure I will get lots of use out of it. How about a containerised version to avoid having to build and self host; multi-arch? That way it can be pulled and run easily on local systems, or deployed elsewhere. Not to mention of course sticking with the Balena theme.

**Comment by Razikus** [comment]
Just added, check https://github.com/Razikus/open-balena-dashboard/blob/master/buildlocal.sh.sh to build not over balena, or deploy it to some application via normal balena process
