### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by markFieldman** [Razikus/open-balena-dashboard#2]
Hi, dear Razikus!
I'm currently working with openBalena and implement parts of its solutions by myself.
Your dashboard is stunning and must be clear - so helpful for me.
Currently, I`m trying to solve the problem of pushing data to openBalena registry via GitHub actions using the custom scenario.
[OpenBalenaCLI GithubAction](https://github.com/Solar-Control/open-balena-cli-action)
But for this moment have no idea about the next steps.
If you need so - I have an idea of how to ensure the main openBalena to use with your dashboard builtin.
So underline my main proposal:
1) Integrate your dashboard as part of openBalena server
2) Automate development of apps, and image creation using Github Actions
3) Customize Quzar with new styles to make it more user-friendly

Waiting for your response!

**Comment by Razikus** [comment]
Hello Mark!

It's very good idea to make something like this.
I would prefer to make more "agnostic" balena builder schema
Something like Git Hook (https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)
So scenario here can be like balena cloud - push to special open-balena-git repository -> hook executing balena build -> logs streamed to terminal

But then we are losing the power of Github Actions and build-in server. But anyway it can be still integrated to Open Balena.

We have working solution with GitlabCI that is building and pushing data over registry. It can even pull images from private repo.
It uses also my other repo that is logging in before any action specified
https://github.com/Razikus/balena-dockerized-cli


It's very simple here
```yaml
docker-deploy-master:
  image: razikus/balena-dockerized-cli:11.35.5
  services:
    - docker:dind
  script:
    - >
      echo -e "'registry.gitlab.com':" >> /registry-secrets.yml
    - >
      echo -e "    username: '$BASEIMAGELOGIN'" >> /registry-secrets.yml
    - > 
      echo -e "    password: '$BASEIMAGEPASSWORD'" >> /registry-secrets.yml
    - DEBUG=1 balena deploy blabla --source . --emulated --build --nocache -h docker -p 2375 --logs --registry-secrets /registry-secrets.yml --buildArg BLABLA=$BLABLA"

````

**Comment by markFieldman** [comment]
> Hello Mark!
> 
> It's very good idea to make something like this.
> I would prefer to make more "agnostic" balena builder schema
> Something like Git Hook (https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)
> So scenario here can be like balena cloud - push to special open-balena-git repository -> hook executing balena build -> logs streamed to terminal
> 
> But then we are losing the power of Github Actions and build-in server. But anyway it can be still integrated to Open Balena.
> 
> We have working solution with GitlabCI that is building and pushing data over registry. It can even pull images from private repo.
> It uses also my other repo that is logging in before any action specified
> https://github.com/Razikus/balena-dockerized-cli
> 
> It's very simple here
> 
> ```yaml
> docker-deploy-master:
>   image: razikus/balena-dockerized-cli:11.35.5
>   services:
>     - docker:dind
>   script:
>     - >
>       echo -e "'registry.gitlab.com':" >> /registry-secrets.yml
>     - >
>       echo -e "    username: '$BASEIMAGELOGIN'" >> /registry-secrets.yml
>     - > 
>       echo -e "    password: '$BASEIMAGEPASSWORD'" >> /registry-secrets.yml
>     - DEBUG=1 balena deploy blabla --source . --emulated --build --nocache -h docker -p 2375 --logs --registry-secrets /registry-secrets.yml --buildArg BLABLA=$BLABLA"
> ```
> 
> We should think about it and make some decision

It is here https://docs.solar-control.tech/openbalena/open-balena-push-analog.
Commit in master repo is actions which is signalize that your code is need to be builded and push widely to all devices.
Dividing by profiles/branches is also good practice in development flow, like:
master -> production
develop -> develop application
feature/* -> your feature envs.
Using my action you are have possibility to execute os configure, or preload command, to upload your customized images  as artifacts directly in repo with project.

**Comment by Razikus** [comment]
Wow it looks very nice.
Sorry i'm not very familiar with Github actions but it looks like Gitlab CICD

Is it 100% free? Any running worker is free or there are some free running hours available?

With super-nice scenario we can even integrate open-balena-dashboard with automatically creation of your actions within it
https://docs.github.com/en/rest/reference/actions#enable-a-selected-repository-for-github-actions-in-an-organization

**Comment by markFieldman** [comment]
@Razikus 
It has default worker limits, like 72 hours for one build, and 1000 API requests in an hour - so limits so low.
It is 100% free of the cause of self-hosting.
And it is possible to add SHA to the application variables for checking release versions too)
Github allows to use API, so we can create it directly into the dashboard to provide BalenaCloud functionality in OpenSouce project :)

**Comment by markFieldman** [comment]
Hi! Can you provide a forking possibility, please?
Now I'm working with improving the UI side, and cannot create a fork from your repo :(
