### ISSUE TITLE
Local Connection

### ISSUE THREAD

**Issue by HonakerM** [Razikus/open-balena-dashboard#4]
I would love if the site could connect to a local instance of balena without having to specify the url. It would most likely require a nginx reverse proxy to handle the front-end api calls but it should not be to hard to implement. I've forked the repo but have not started work on it yet. 

@Razikus What are your thoughts?

**Comment by Razikus** [comment]
Hey
So basicaly you want to include frontend inside your open balena instance, right? 
I'm considering trying to somehow achieve compatibility with it, but still much to do

**Comment by Razikus** [comment]
Like i said - we are going on the compatibility with Balena, but it will take time and work
