### ISSUE TITLE
CORS Error on login

### ISSUE THREAD

**Issue by HonakerM** [Razikus/open-balena-dashboard#5]
When trying to access my openbalena instance I get the following two errors in console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxxx/connections. (Reason: CORS request did not succeed).
2
Uncaught (in promise) Error: Network Error
```

**Comment by Razikus** [comment]
Do you have self signed https?

**Comment by HonakerM** [comment]
Yes. I'm using the basic open-balena install

**Comment by p0thi** [comment]
@Razikus how to not use the self signed cert? Is there a simple way to use official certificates like Let's Encrypt?

**Comment by Razikus** [comment]
You must debug it somehow yourself unfortunately, if you have more problems - contact me on e-mail or via discord Razikus#5125
